"use client";

import { useEffect, useRef, useState } from "react";
import { motion } from "framer-motion";
import { Radio, Heart, Smile, Activity, DollarSign } from "lucide-react";

const features = [
  {
    icon: Radio,
    title: "NVIDIA MiniMax AI Task Engine",
    desc: "One fresh, personalised couple activity every day — generated by MiniMax M2.7 using both partners' love languages, interests, comfort levels, and real-time mood. Never repetitive.",
    span: "col-span-1 md:col-span-3",
    variant: "dark" as const,
    tags: ["Communication", "Adventure", "Care", "Fun", "Reflection", "Creative"],
  },
  {
    icon: Heart,
    title: "Sentiment-Driven Adaptation",
    desc: "Your feedback teaches the AI. Sentiment scores from your last 5 tasks shape the next one — so Heart2Heart gets smarter every single day you use it together.",
    span: "col-span-1 md:col-span-3",
    variant: "rose" as const,
    bar: 92,
  },
  {
    icon: Smile,
    title: "Daily Mood Check-in",
    desc: "Log your mood in seconds. Choose whether to share it — if you do, it feeds directly into the AI prompt.",
    span: "col-span-1 md:col-span-2",
    variant: "light" as const,
  },
  {
    icon: Activity,
    title: "Engagement Score",
    desc: "A composite score combining task completion, ratings, and sentiment — updated live on your shared dashboard.",
    span: "col-span-1 md:col-span-2",
    variant: "light" as const,
  },
  {
    icon: DollarSign,
    title: "Relationship Timeline",
    desc: "Auto-generated milestones — first task, 7-day streak, highest-rated activity — all in a beautiful scrollable timeline.",
    span: "col-span-1 md:col-span-2",
    variant: "light" as const,
  },
];

const cardVariants = {
  hidden: { opacity: 0, y: 28 },
  visible: (i: number) => ({
    opacity: 1,
    y: 0,
    transition: { delay: i * 0.1, duration: 0.6, ease: [0.23, 1, 0.32, 1] as const },
  }),
};

export default function FeaturesBento() {
  const ref = useRef<HTMLDivElement>(null);
  const [vis, setVis] = useState(false);

  useEffect(() => {
    const obs = new IntersectionObserver(
      ([e]) => { if (e.isIntersecting) setVis(true); },
      { threshold: 0.1 }
    );
    if (ref.current) obs.observe(ref.current);
    return () => obs.disconnect();
  }, []);

  const bgMap = {
    dark: "bg-[#0D0D12]",
    rose: "bg-brand-rose",
    light: "bg-white",
  };
  const titleMap = {
    dark: "text-white",
    rose: "text-white",
    light: "text-[#0D0D12]",
  };
  const descMap = {
    dark: "text-[rgba(255,255,255,0.45)]",
    rose: "text-[rgba(255,255,255,0.8)]",
    light: "text-[rgba(13,13,18,0.6)]",
  };
  const iconBgMap = {
    dark: "bg-[rgba(255,255,255,0.07)]",
    rose: "bg-[rgba(255,255,255,0.18)]",
    light: "bg-[rgba(232,39,75,0.07)]",
  };
  const icoMap = {
    dark: "text-[rgba(255,255,255,0.6)]",
    rose: "text-white",
    light: "text-brand-rose",
  };

  return (
    <section id="features" className="py-[80px] md:py-[120px] px-6 md:px-16 bg-[rgba(13,13,18,0.02)] relative z-10 overflow-hidden">
      <div className="max-w-[1240px] mx-auto relative z-[1]">
        <motion.div initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-[11px] font-semibold tracking-[0.2em] uppercase text-brand-rose mb-5">
          Platform Features
        </motion.div>
        <motion.h2 initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.1 }} className="font-serif text-[40px] md:text-[58px] font-bold tracking-[-3px] leading-[0.93] text-[#0D0D12]">
          Everything your relationship<br /><em className="italic text-brand-rose">actually needs</em>
        </motion.h2>
        <motion.p initial={{ opacity: 0, y: 24 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: 0.2 }} className="text-[17px] font-light text-[rgba(13,13,18,0.6)] leading-[1.75] max-w-[480px] mt-5">
          Built to the Platinum standard — intelligent task generation, real-time mood sync, and deep relationship analytics.
        </motion.p>

        <div ref={ref} className="grid grid-cols-1 md:grid-cols-6 gap-4 mt-16">
          {features.map((f, i) => (
            <motion.div
              key={i}
              custom={i}
              variants={cardVariants}
              initial="hidden"
              animate={vis ? "visible" : "hidden"}
              className={`${f.span} ${bgMap[f.variant]} border border-[rgba(13,13,18,0.08)] rounded-[28px] p-9 relative overflow-hidden hover:-translate-y-[6px] hover:shadow-[0_20px_60px_rgba(13,13,18,0.08)] transition-all duration-[400ms] ease-[cubic-bezier(0.23,1,0.32,1)] ${f.variant === "dark" ? "hover:border-[rgba(232,39,75,0.35)]" : f.variant === "rose" ? "hover:scale-[1.01]" : "hover:border-[rgba(232,39,75,0.15)]"}`}
            >
              <div className={`w-12 h-12 rounded-[16px] ${iconBgMap[f.variant]} flex items-center justify-center mb-[22px]`}>
                <f.icon size={22} className={icoMap[f.variant]} strokeWidth={2} />
              </div>
              <div className={`font-serif text-[21px] font-bold ${titleMap[f.variant]} mb-[10px] tracking-[-0.4px]`}>{f.title}</div>
              <p className={`text-[14px] font-light ${descMap[f.variant]} leading-[1.7]`}>{f.desc}</p>
              {f.tags && (
                <div className="flex gap-2 flex-wrap mt-5">
                  {f.tags.map((t) => (
                    <span key={t} className="bg-[rgba(255,255,255,0.12)] rounded-full px-3 py-[5px] text-[12px] text-[rgba(255,255,255,0.7)]">{t}</span>
                  ))}
                </div>
              )}
              {f.bar && (
                <>
                  <div className="h-[6px] rounded-[6px] bg-[rgba(232,39,75,0.1)] overflow-hidden mt-5">
                    <div className="h-full rounded-[6px] bg-gradient-to-r from-brand-rose to-[#F97316]" style={{ width: `${f.bar}%` }} />
                  </div>
                  <div className="flex justify-between mt-2 text-[11px] text-[rgba(255,255,255,0.6)]">
                    <span>Adapting to you</span><span>{f.bar}% match</span>
                  </div>
                </>
              )}
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
